[paths]
included_dirs = [
    "workflow",
    "workflow/daemon",
    "workflow/model_service",
]

[api]
enabled = false
host = "0.0.0.0"
# port will be set to random if not specified
use_random_port = true
debug = false
