[paths]
included_dirs = [
    "workflow",
    "workflow/daemon",
    "workflow/model_service",
]

[api]
enabled = false
host = "0.0.0.0"
port = null  # null means use random port
use_random_port = true
debug = false
