"""
Onboarding wizard for new MCLI users.

Provides interactive and non-interactive setup modes to configure
MCLI with validated settings.
"""

import os
from pathlib import Path

import click
from rich.prompt import Confirm, Prompt
from rich.table import Table

from mcli.lib.logger.logger import get_logger
from mcli.lib.ui.styling import console, info, success

logger = get_logger(__name__)


def _write_env_file(env_dict: dict, path: Path):
    """Write a validated env dict to a .env file, preserving existing keys."""
    existing = {}
    if path.exists():
        for line in path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, val = line.partition("=")
                existing[key.strip()] = val.strip()

    merged = {**existing, **env_dict}

    lines = ["# MCLI Configuration (generated by mcli setup)", ""]
    for key in sorted(merged):
        lines.append(f"{key}={merged[key]}")
    lines.append("")

    path.write_text("\n".join(lines))


def _write_config_toml(included_dirs: list, path: Path):
    """Write a config.toml with paths configuration."""
    dirs_str = ", ".join(f'"{d}"' for d in included_dirs)
    content = f"""# MCLI Configuration
# Generated by mcli setup

[paths]
included_dirs = [{dirs_str}]
"""
    path.write_text(content)


def _run_minimal_setup():
    """Minimal setup: just create directories and default config."""
    from mcli.lib.config.settings import MCLISettings

    settings = MCLISettings()
    home = settings.home_path
    home.mkdir(parents=True, exist_ok=True)
    (home / "workflows").mkdir(exist_ok=True)

    config_toml = home / "config.toml"
    if not config_toml.exists():
        _write_config_toml(settings.included_dirs, config_toml)

    return settings


def _run_interactive_setup():
    """Interactive setup: ask user for configuration choices."""
    from mcli.lib.config.settings import MCLISettings

    console.print()
    console.print("[bold cyan]MCLI Setup Wizard[/bold cyan]")
    console.print("[dim]Configure your MCLI installation step by step.[/dim]")
    console.print()

    env_overrides = {}

    # Step 1: Environment
    env = Prompt.ask(
        "[cyan]Environment[/cyan]",
        choices=["development", "staging", "production"],
        default="development",
    )
    if env != "development":
        env_overrides["MCLI_ENV"] = env

    # Step 2: Editor
    default_editor = os.getenv("EDITOR", "vim")
    editor = Prompt.ask("[cyan]Preferred editor[/cyan]", default=default_editor)
    if editor != "vim":
        env_overrides["EDITOR"] = editor

    # Step 3: API keys (optional)
    console.print()
    console.print("[bold]API Keys[/bold] [dim](optional, press Enter to skip)[/dim]")

    openai_key = Prompt.ask("[cyan]OpenAI API key[/cyan]", default="", show_default=False)
    if openai_key:
        env_overrides["OPENAI_API_KEY"] = openai_key

    anthropic_key = Prompt.ask("[cyan]Anthropic API key[/cyan]", default="", show_default=False)
    if anthropic_key:
        env_overrides["ANTHROPIC_API_KEY"] = anthropic_key

    # Step 4: Debug mode
    console.print()
    if Confirm.ask("[cyan]Enable debug mode?[/cyan]", default=False):
        env_overrides["MCLI_DEBUG"] = "1"

    # Build validated settings
    settings = MCLISettings(**env_overrides, _env_file=None)

    # Create directories
    home = settings.home_path
    home.mkdir(parents=True, exist_ok=True)
    (home / "workflows").mkdir(exist_ok=True)

    # Write config files
    env_dict = settings.to_env_dict()
    env_dict.update({k: v for k, v in env_overrides.items() if k not in env_dict and v})

    if env_dict:
        env_path = Path.cwd() / ".env"
        _write_env_file(env_dict, env_path)
        console.print(f"[green]\u2713[/green] Wrote .env to {env_path}")

    config_toml = home / "config.toml"
    if not config_toml.exists():
        _write_config_toml(settings.included_dirs, config_toml)
        console.print(f"[green]\u2713[/green] Wrote config.toml to {config_toml}")

    return settings


@click.command("setup")
@click.option("--minimal", is_flag=True, help="Minimal setup (directories + defaults only)")
@click.option("--full", is_flag=True, help="Full setup with all optional features")
def setup(minimal, full):
    """Interactive setup wizard for new users.

    Configures MCLI with validated settings, creates necessary directories,
    and writes configuration files.

    Examples:
        mcli setup              # Interactive wizard
        mcli setup --minimal    # Directories + defaults only
        mcli setup --full       # All features configured
    """
    from mcli.lib.config.settings import MCLISettings

    if minimal:
        settings = _run_minimal_setup()
        success("Minimal setup complete!")
    elif full:
        # Full mode: same as interactive but with all prompts
        settings = _run_interactive_setup()
    else:
        settings = _run_interactive_setup()

    # Summary table
    console.print()
    table = Table(title="Setup Summary", show_header=False)
    table.add_column("Setting", style="cyan")
    table.add_column("Value", style="green")

    table.add_row("Environment", settings.mcli_env)
    table.add_row("Home Directory", str(settings.home_path))
    table.add_row("Workflows", str(settings.workflows_dir))
    table.add_row("Editor", settings.editor)
    table.add_row("Debug Mode", "Yes" if settings.is_debug else "No")
    table.add_row("OpenAI API", "Configured" if settings.has_api_key("openai") else "Not set")
    table.add_row(
        "Anthropic API",
        "Configured" if settings.has_api_key("anthropic") else "Not set",
    )

    console.print(table)
    console.print()

    # Next steps
    console.print("[bold]Next Steps:[/bold]")
    console.print("  1. Initialize workflows:  [cyan]mcli init[/cyan]")
    console.print("  2. Create a command:      [cyan]mcli new my-command[/cyan]")
    console.print("  3. Run a command:         [cyan]mcli run my-command[/cyan]")
    console.print()
