# Streamlit Cloud Secrets Configuration
# This file is for reference - actual secrets are configured in Streamlit Cloud UI
# Go to: https://share.streamlit.io → Your app → Settings → Secrets

# =============================================================================
# SUPABASE CONFIGURATION (Required)
# =============================================================================
SUPABASE_URL = "https://uljsqvwkomdrlnofmlad.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsanNxdndrb21kcmxub2ZtbGFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDIyNDQsImV4cCI6MjA3MjM3ODI0NH0.QCpfcEpxGX_5Wn8ljf_J2KWjJLGdF8zRsV_7OatxmHI"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsanNxdndrb21kcmxub2ZtbGFkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjgwMjI0NCwiZXhwIjoyMDcyMzc4MjQ0fQ.4364sQbTJQd4IcxEQG6mPiOUw1iJ2bdKfV6W4oRqHvs"

# =============================================================================
# LSH DAEMON INTEGRATION (Production)
# =============================================================================
# Point to deployed LSH daemon on Fly.io
LSH_API_URL = "https://mcli-lsh-daemon.fly.dev"

# =============================================================================
# INSTRUCTIONS FOR STREAMLIT CLOUD
# =============================================================================
# 1. Go to https://share.streamlit.io
# 2. Select your app (web-mcli or create new)
# 3. Click "Settings" → "Secrets"
# 4. Copy the contents above (without comments) and paste into the secrets editor
# 5. Click "Save"
#
# The secrets will be available as environment variables in your Streamlit app
# via os.getenv() or st.secrets
#
# DO NOT commit this file if it contains real credentials
# This file is already in .gitignore for safety
