# =============================================================================
# STREAMLIT CLOUD SECRETS - COPY THIS ENTIRE CONTENT TO STREAMLIT CLOUD
# =============================================================================
# Instructions:
# 1. Go to https://share.streamlit.io
# 2. Select your app → Settings → Secrets
# 3. Copy EVERYTHING below this line and paste into the secrets editor
# 4. Click "Save"
# =============================================================================

# UK Companies House API (Required for UK corporate data)
UK_COMPANIES_HOUSE_API_KEY = "your_companies_house_api_key_here"

# Alpaca Trading API - Paper Trading (Required for trading features)
ALPACA_API_KEY = "your_alpaca_api_key_here"
ALPACA_SECRET_KEY = "your_alpaca_secret_key_here"
ALPACA_BASE_URL = "https://paper-api.alpaca.markets"

# Supabase Configuration (Required for database)
SUPABASE_URL = "https://uljsqvwkomdrlnofmlad.supabase.co"
SUPABASE_KEY = "your_anon_key_here"
SUPABASE_SERVICE_ROLE_KEY = "your_service_role_key_here"

# LSH Daemon Configuration (Production)
LSH_API_URL = "https://mcli-lsh-daemon.fly.dev"
LSH_API_KEY = "your_lsh_api_key_here"

# Database Configuration
DATABASE_URL = "postgresql://postgres:your_password@db.uljsqvwkomdrlnofmlad.supabase.co:5432/postgres"

# MLflow Configuration
MLFLOW_TRACKING_URI = "http://localhost:5000"
MLFLOW_EXPERIMENT_NAME = "politician_trading"

# Environment Settings
ENVIRONMENT = "production"
DEBUG = "false"

# =============================================================================
# OPTIONAL - Add these when you obtain the API keys
# =============================================================================
# OPENCORPORATES_API_KEY = "your_key_when_approved"
# XBRL_US_API_KEY = "your_key_from_xbrl_us"
# FINNHUB_API_KEY = "your_key_from_finnhub"
