# =============================================================================
# STREAMLIT CLOUD SECRETS - COPY THIS ENTIRE CONTENT TO STREAMLIT CLOUD
# =============================================================================
# Instructions:
# 1. Go to https://share.streamlit.io
# 2. Select your app → Settings → Secrets
# 3. Copy EVERYTHING below this line and paste into the secrets editor
# 4. Click "Save"
# =============================================================================

# UK Companies House API (Required for UK corporate data)
UK_COMPANIES_HOUSE_API_KEY = "18c9e5c4-556f-40cf-943b-7057f31f8128"

# Alpaca Trading API - Paper Trading (Required for trading features)
ALPACA_API_KEY = "PKA8W60S0UVTDHBHEPTA"
ALPACA_SECRET_KEY = "NoD8YBcuhGHWZ8QAwDvUL1QzcjrU7eDUXwrBgHJF"
ALPACA_BASE_URL = "https://paper-api.alpaca.markets"

# Supabase Configuration (Required for database)
SUPABASE_URL = "https://uljsqvwkomdrlnofmlad.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsanNxdndrb21kcmxub2ZtbGFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDIyNDQsImV4cCI6MjA3MjM3ODI0NH0.QCpfcEpxGX_5Wn8ljf_J2KWjJLGdF8zRsV_7OatxmHI"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsanNxdndrb21kcmxub2ZtbGFkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjgwMjI0NCwiZXhwIjoyMDcyMzc4MjQ0fQ.4364sQbTJQd4IcxEQG6mPiOUw1iJ2bdKfV6W4oRqHvs"

# LSH Daemon Configuration (Production)
LSH_API_URL = "https://mcli-lsh-daemon.fly.dev"
LSH_API_KEY = "xK7mP9nQ2sT4vW8yZ1bC3dF5gH7jK9mN0pR2tV4wX6zA8cE0"

# Database Configuration
DATABASE_URL = "postgresql://postgres:your_password@db.uljsqvwkomdrlnofmlad.supabase.co:5432/postgres"

# MLflow Configuration
MLFLOW_TRACKING_URI = "http://localhost:5000"
MLFLOW_EXPERIMENT_NAME = "politician_trading"

# Environment Settings
ENVIRONMENT = "production"
DEBUG = "false"

# =============================================================================
# OPTIONAL - Add these when you obtain the API keys
# =============================================================================
# OPENCORPORATES_API_KEY = "your_key_when_approved"
# XBRL_US_API_KEY = "your_key_from_xbrl_us"
# FINNHUB_API_KEY = "your_key_from_finnhub"
